title: Kubíkovo
author: chamik
author_realname: Jakub Hampl
type: Person

tagline: Just another page on the interwebs.
description: >-
  Just another page on the interwebs.
  Personal site of Jakub Hampl, also known as Kubík or chamik.
logo: /src/assets/images/pfp.png
timezone: Europe/Prague

url: "https://chamik.eu"

github_username: chamik
twitter:
  username: kub1k_h
  card: summary

social:
  name: chamik
  links:
    - https://twitter.com/kub1k_h
    - https://www.wikidot.com/user:info/chamik
    - https://github.com/chamik
    - https://linkedin.com/in/chamik/
    - https://steamcommunity.com/id/chamik/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-postcss
  - jekyll-redirect-from

postcss:
  cache: false

permalink: pretty

markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

source: src/

exclude: [
  .gitignore,
  styles/index.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  tailwind.config.js,
  README.md,
  build/,
]