title: Jekyll Tailwind Template
description: Basic Jekyll site template using Tailwind CSS with PostCSS

url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag
  - jekyll-postcss

postcss:
  cache: false

source: src/

exclude: [
  .gitignore,
  styles/index.css,
  package.json,
  package-lock.json,
  postcss.config.js,
  tailwind.config.js,
  README.md,
  build/,
]